spring:
  profiles:
    active: MAIN
  jpa:
    open-in-view: true
server:
  port: 8080
app:
  api:
    geocode:
      type: COORDS
      url: https://geocode.xyz
      query:
        region: ES
        geoit: json
        auth: 338345084377716207075x50864
    travelpayouts:
      type: NAME
      url: http://autocomplete.travelpayouts.com/places2
      query:
        locale: ES
        types[]: city
    openweathermap:
      type: WEATHER
      name: Clima
      description: Informacion actual sobre el estado metrológico
      icon: http://openweathermap.org/img/wn/{icon}@2x.png
      url: https://api.openweathermap.org/data/2.5/onecall
      query:
        lang: ES
        units: metric
        exclude: current,minutely,hourly,alerts
        appid: bb4f6eaa03d8741b67f9d37138cf28d9
    ticketmaster:
      type: EVENTS
      name: Eventos
      description: Informacion diaria sobre eventos proximos
      url: https://app.ticketmaster.com/discovery/v2/events.json
      query:
        unit: km
        local: ES
        radius: 100
        countyCode: ES
        apikey: oun77uH0nt2TtvqJCywGlPOw7kHlvEDu
    newsdata:
      type: NEWS
      name: Noticias
      description: Informacion diaria sobre las noticias del último momento
      url: https://newsdata.io/api/1/news
      query:
        country: ES
        language: ES
        apikey: pub_32790974bd5ce266b23c8204a3c0047ebbfd
    currents:  # Unresponsive
      type: NEWS
      name: Noticias
      description: Informacion diaria sobre las noticias del último momento
      url: https://api.currentsapi.services/v1/latest-news
      query:
        region: ES
        language: ES
        apiKey: DEGB9B4zVcjuviCwA5jzR_ZDkajWMlG3MaenO-UGZWNtn-yb
    newsapi:  # Unlocalized
      type: NEWS
      name: Noticias
      description: Informacion diaria sobre las noticias del último momento
      url: https://newsapi.org/v2/top-headlines
      query:
        country: ES
        apiKey: 5085f201079f402f9846ff38b481d04d
---
spring:
  config:
    activate:
      on-profile: MAIN
  datasource:
    url: jdbc:h2:file:./database
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
app:
  configuration:
    timeout: 8s
---
spring:
  config:
    activate:
      on-profile: TEST
  datasource:
    url: jdbc:h2:mem:database;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
app:
  configuration:
    timeout: 64s